Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2022-08, with the labels that each got.

#46 Update module path to match repo path
  example/example.go
  go.mod
  version_test.go
Labels: version: bump patch, type: maintenance

#47 Prepare v0.1.1 release
  CHANGELOG.md
  version.go
Labels: version: bump patch, type: maintenance

#60 More descriptive errors
  common.go
  honeycomb.go
  honeycomb_test.go
Labels: version: bump patch, type: maintenance

#55 Set log level to debug when debug option is set
  honeycomb.go
  honeycomb_test.go
Labels: type: bug, version: bump patch

#57 Add missing license headers
  deterministic_sampler.go
  deterministic_sampler_test.go
  honeycomb_test.go
  version.go
  version_test.go
Labels: version: bump patch, type: maintenance

#58 Add baggage processor tests
  baggage_span_processor_test.go
Labels: type: enhancement, version: bump patch

#56 Set base exporter endpoint when setting up vendor opts
  honeycomb.go
  honeycomb_test.go
Labels: type: bug, version: bump patch

#61 Prepare v0.1.2 release
  CHANGELOG.md
  version.go
Labels: version: bump patch, type: maintenance

#64 feat: add OTLP version header
  RELEASING.md
  honeycomb.go
  honeycomb_test.go
Labels: type: enhancement, version: bump patch

#65 Add support for Honeycomb endpoint environment variables
  honeycomb.go
  honeycomb_test.go
Labels: type: enhancement, version: bump minor

#68 docs: add webhook triggers example
  examples/webapp/example.go
  examples/webhook-listener-triggers/README.md
  examples/webhook-listener-triggers/go.mod
  examples/webhook-listener-triggers/go.sum
  examples/webhook-listener-triggers/main.go
Labels: type: documentation, version: no bump, merge at will

#70 Disable metrics by default
  honeycomb.go
  honeycomb_test.go
Labels: type: bug, version: bump minor

#72 Add support for separate traces and metrics API key and dataset
  go.mod
  go.sum
  honeycomb.go
  honeycomb_test.go
Labels: type: enhancement, version: bump minor

#66 Prototype of local visualizations like .NET
  common.go
  honeycomb.go
  honeycomb_test.go
  span_link_exporter.go
  spank_link_exporter_test.go
Labels: type: enhancement, version: bump minor

#73 Prepare v0.2.0 release
  CHANGELOG.md
  version.go
Labels: version: bump minor, type: maintenance
