Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2022-12, with the labels that each got.

#93 chore: Give dependabot PRs a better title
  .github/dependabot.yml
Labels: version: no bump, merge at will, no-changelog

#98 fix: Don't error on misconfiguration; warn instead
  honeycomb.go
  honeycomb_test.go
Labels: type: bug, version: bump patch

#99 maint: fix typo in test file
  span_link_exporter_test.go
Labels: merge at will, no-changelog, version: no-bump
