Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2022-10, with the labels that each got.

#79 maint: add release file
  .github/release.yml
Labels: version: no bump, merge at will, type: maintenance, no-changelog

#81 Remove timestamp field from example trigger hook
  examples/webhook-listener-triggers/README.md
Labels: version: no bump, type: maintenance, no-changelog

#82 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
Labels: version: no bump, merge at will, type: maintenance

#80 Update launcher to latest
  go.mod
  go.sum
Labels: version: bump patch, type: maintenance

#87 prepare 0.3.0
  CHANGELOG.md
  honeycomb.go
  version.go
Labels: type: maintenance, no-changelog

#88 maint: update readme with latest otel version
  README.md
  RELEASING.md
Labels: type: documentation, version: no bump, merge at will, no-changelog
