Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2023-01, with the labels that each got.

#100 maint: Update Launcher and OTel packages
  go.mod
  go.sum
Labels: version: bump patch, type: maintenance

#101 rel: Prepare v0.4.0 release
  CHANGELOG.md
  README.md
  version.go
Labels: type: maintenance

#102 maint: add smoke tests for traces
  Makefile
  examples/webhook-listener-triggers/.dockerignore
  examples/webhook-listener-triggers/Dockerfile
  examples/webhook-listener-triggers/go.mod
  examples/webhook-listener-triggers/go.sum
  examples/webhook-listener-triggers/main.go
  smoke-tests/apps/.gitkeep
  smoke-tests/collector/data-results/.gitkeep
  smoke-tests/collector/otel-collector-config.yaml
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance

#103 fix: Use configured logger to print messages
  honeycomb.go
  honeycomb_test.go
Labels: type: bug

#107 maint: add smoke test to circle
  .circleci/config.yml
Labels: version: no bump, type: maintenance

#109 maint: Update launcher to use new repo
  README.md
  examples/webapp/example.go
  examples/webhook-listener-triggers/go.mod
  examples/webhook-listener-triggers/go.sum
  examples/webhook-listener-triggers/main.go
  go.mod
  go.sum
  honeycomb.go
  honeycomb_test.go
Labels: version: bump patch, type: maintenance

#108 rel: Prepare v0.4.1 release
  CHANGELOG.md
  version.go
Labels: version: bump patch, type: maintenance

#110 ci: fix filters for smoke-tests job
  .circleci/config.yml
Labels: version: no bump, type: maintenance, no-changelog
