Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2023-04, with the labels that each got.

#131 maint: update oss badge to active
  OSSMETADATA
Labels: merge at will, type: maintenance, no-changelog

#132 rel: prepare release 0.5.2
  CHANGELOG.md
  version.go
Labels: no-changelog

#133 ci: add go 1.20 to ci
  .circleci/config.yml
Labels: type: maintenance, no-changelog

#135 maint: Update launcher & set default endpoint
  examples/baggage/go.mod
  examples/baggage/go.sum
  examples/webhook-listener-triggers/go.mod
  examples/webhook-listener-triggers/go.sum
  go.mod
  go.sum
  go.work.sum
  honeycomb.go
  honeycomb_test.go
Labels: type: maintenance

#136 rel: Prepare v0.5.3 release
  CHANGELOG.md
  version.go
Labels: type: maintenance

#138 maint: otel-launcher-go rename to otel-config-go
  README.md
  examples/baggage/example.go
  examples/baggage/go.mod
  examples/baggage/go.sum
  examples/webhook-listener-triggers/go.mod
  examples/webhook-listener-triggers/go.sum
  examples/webhook-listener-triggers/main.go
  go.mod
  go.sum
  honeycomb.go
  honeycomb_test.go
Labels: version: bump patch, type: maintenance

#139 rel: v0.5.4
  CHANGELOG.md
  version.go
Labels: version: no bump, type: maintenance, no-changelog
