Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2024-03, with the labels that each got.

#193 feat: support Classic Ingest Keys
  honeycomb.go
  honeycomb_test.go
Labels: type: enhancement, merge at will, version: bump minor

#195 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: version: no bump, type: maintenance, no-changelog

#194 rel: Prepare v0.10.0 release
  CHANGELOG.md
  README.md
  version.go
Labels: no-changelog

#196 maint: Update ubuntu image in workflows to latest
  .circleci/config.yml
Labels: type: maintenance, version: no-bump
