Repository honeycombio/honeycomb-opentelemetry-go, pull requests merged in 2024-04, with the labels that each got.

#202 maint: update otel dependencies to 1.25.0
  .circleci/config.yml
  examples/baggage/go.mod
  examples/baggage/go.sum
  examples/webhook-listener-triggers/Dockerfile
  examples/webhook-listener-triggers/go.mod
  examples/webhook-listener-triggers/go.sum
  go.mod
  go.sum
  go.work
  go.work.sum
  honeycomb.go
  honeycomb_test.go
Labels: version: bump minor, breaking-change

#206 maint: Update project status and add status link in README
  OSSMETADATA
  README.md
Labels: version: no bump, type: maintenance

#207 maint: Update README title
  README.md
Labels: version: no bump, type: maintenance, no-changelog
